### ISSUE TITLE
on new installation, appear to be missing auth (using new-style token)

### ISSUE THREAD

**Issue by titaniumbones** [sgratzl/slack-cleaner#77]
**Describe the bug**
It is no longer possible to create legacy tokens. I have created a new app with new-style tokens and am unable to use the tool. 

**To Reproduce**
1. Create a new app in a new workspace
2. Do your best to assign relevant scopes
3. Confirm that you are able to access the workspace with `slack-cleaner --info`
4. Attempt to delete messages (even without `--perform`)

**Expected behavior**
messages to be deleted should be listed.

**Desktop (please complete the following information):**
 - OS: Arch Linux

**Additional context**
I've confirmed that identical operations succeed when used with an older install/token.

**Comment by sgratzl** [comment]
reason: https://api.slack.com/changelog/2020-01-deprecating-antecedents-to-the-conversations-api

certain APIs are deprecated in favor or new ones and new apps aren't allowed to use them anymore

**Comment by titaniumbones** [comment]
Thanks -- I guess this is a feature request then, not a bug report :-/
 
On Thu, May 07 2020, Samuel Gratzl wrote:

> reason: https://api.slack.com/changelog/2020-01-deprecating-antecedents-to-the-conversations-api
>
> certain APIs are deprecated in favor or new ones and new apps aren't allowed to use them anymore


--

**Comment by sgratzl** [comment]
should be fixed with v0.7.2

**Comment by titaniumbones** [comment]
Hmm.  a couple of issues remaining

- I had to add hte bot to the channel manually (seems like that may be required now)
- messages are not actually deleted when runningiwth `--perform`.  Instead I get a series of these JSON error messages:
```
Failed to delete (invalid_arguments)->
{   'blocks': [   {   'block_id': 'r7WZr',
                      'elements': [   {   'elements': [   {   'text': 'Suggestion '
                                                                      'to '
                                                                      'earning '
                                                                      'an '
                                                                      'extra '
                                                                      'credit '
                                                                      'through '
                                                                      'an '
                                                                      'assignment.',
                                                              'type': 'text'}],
                                          'type': 'rich_text_section'}],
                      'type': 'rich_text'}],
    'client_msg_id': '16d47f45-4e98-4999-8161-9be2774afeb7',
    'team': 'TTE5A90B0',
    'text': 'Suggestion to earning an extra credit through an assignment.',
    'ts': '1584058521.000600',
    'type': 'message',
    'user': 'UT0NR4B1R'}
```
what do you think is going on?

**Comment by sgratzl** [comment]
>     * messages are not actually deleted when runningiwth `--perform`.  Instead I get a series of these JSON error messages:

have  you tried the `--as_user` argument?

> I had to add hte bot to the channel manually (seems like that may be required now)

are you using **user token scopes**?

**Comment by wssyncmldm** [comment]
using `--as_user` is issuing following error:
```
Failed to delete (cant_delete_message)->
```
